INSERT INTO ARTIST (ID_ARTIST, ID_ARTIST_SPOTIFY, NAME) VALUES (1, 'IDTEST1', 'Raimundos');
INSERT INTO ARTIST (ID_ARTIST, ID_ARTIST_SPOTIFY, NAME) VALUES (2, 'IDTEST2', 'U2');
INSERT INTO ARTIST (ID_ARTIST, ID_ARTIST_SPOTIFY, NAME) VALUES (3, 'IDTEST3', 'Red Hot Chilli Pepper');