INSERT INTO CATEGORY (ID_CATEGORY, ID_CATEGORY_SPOTIFY, NAME) VALUES (1, 'pop', 'Pop');
INSERT INTO CATEGORY (ID_CATEGORY, ID_CATEGORY_SPOTIFY, NAME) VALUES (2, 'brazilian', 'Brazilian music');
INSERT INTO CATEGORY (ID_CATEGORY, ID_CATEGORY_SPOTIFY, NAME) VALUES (3, 'classical', 'Classical');
INSERT INTO CATEGORY (ID_CATEGORY, ID_CATEGORY_SPOTIFY, NAME) VALUES (4, 'rock', 'Rock');