INSERT INTO ARTIST (ID_ARTIST, ID_ARTIST_SPOTIFY, NAME) VALUES (1, '0GNq4xh8uFCyihPurnunf7', 'Engenheiros Do Hawaii');

INSERT INTO DISC (ID_DISC, ID_DISC_SPOTIFY, TYPE, ID_CATEGORY, ID_ARTIST, NAME, PRICE)
  VALUES (1, '2kiDkXNxuQME25DEUWiNkw', 'ALBUM', 1, 1, 'O Papa É Pop', 25.5);