INSERT INTO VD_ORDER (ID_ORDER, ID_PERSON, TOTAL, CASHBACK_TOTAL, CREATION_DATE) VALUES (1, 1, 100, 10, sysdate);
INSERT INTO ORDER_ITEM (ID_ORDER_ITEM, ID_ORDER, ID_DISC, QTD, UNIT_PRICE, TOTAL, CASHBACK, CASHBACK_TOTAL) VALUES (1, 1, 1, 2, 5, 10, 10, 10);


INSERT INTO VD_ORDER (ID_ORDER, ID_PERSON, TOTAL, CASHBACK_TOTAL, CREATION_DATE) VALUES (2, 1, 100, 10, '2019-02-10 00:00:00');
INSERT INTO ORDER_ITEM (ID_ORDER_ITEM, ID_ORDER, ID_DISC, QTD, UNIT_PRICE, TOTAL, CASHBACK, CASHBACK_TOTAL) VALUES (2, 2, 2, 2, 5, 10, 10, 10);