server:
  port: 9000

spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

  datasource:
    name: vdsale
    url: jdbc:mariadb://localhost:3306/vdsale
    username: root
    password: 123456

spotify:
  client:
    id: 8153f8d64e0a453cb58cdefdd6564c25
    secret: eef4e5bc6ddd46df89802749f8ff270f