CREATE TABLE IF NOT EXISTS CASHBACK (
  ID_CASHBACK INT NOT NULL AUTO_INCREMENT,
  ID_CATEGORY INT NOT NULL,
  WEEKDAY VARCHAR(15) NOT NULL,
  CASHBACK_VALUE DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (ID_CASHBACK),
  CONSTRAINT ID_CATEGORY_CASHBACK FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY (ID_CATEGORY)
);

INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'pop' ), 'SUNDAY', 25);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'pop' ), 'MONDAY', 7);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'pop' ), 'TUESDAY', 6);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'pop' ), 'WEDNESDAY', 2);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'pop' ), 'THURSDAY', 10);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'pop' ), 'FRIDAY', 15);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'pop' ), 'SATURDAY', 20);

INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'brazilian' ), 'SUNDAY', 30);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'brazilian' ), 'MONDAY', 5);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'brazilian' ), 'TUESDAY', 10);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'brazilian' ), 'WEDNESDAY', 15);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'brazilian' ), 'THURSDAY', 20);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'brazilian' ), 'FRIDAY', 25);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'brazilian' ), 'SATURDAY', 30);

INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'classical' ), 'SUNDAY', 35);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'classical' ), 'MONDAY', 3);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'classical' ), 'TUESDAY', 5);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'classical' ), 'WEDNESDAY', 8);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'classical' ), 'THURSDAY', 13);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'classical' ), 'FRIDAY', 18);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'classical' ), 'SATURDAY', 25);

INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'rock' ), 'SUNDAY', 40);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'rock' ), 'MONDAY', 10);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'rock' ), 'TUESDAY', 15);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'rock' ), 'WEDNESDAY', 15);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'rock' ), 'THURSDAY', 15);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'rock' ), 'FRIDAY', 20);
INSERT INTO CASHBACK (ID_CATEGORY, WEEKDAY, CASHBACK_VALUE)
  VALUES ( (SELECT ID_CATEGORY FROM CATEGORY WHERE ID_CATEGORY_SPOTIFY = 'rock' ), 'SATURDAY', 40);