CREATE TABLE IF NOT EXISTS VD_ORDER (
  ID_ORDER INT NOT NULL AUTO_INCREMENT,
  ID_PERSON INT NOT NULL,
  TOTAL DECIMAL(5,2) NOT NULL,
  CASHBACK_TOTAL DECIMAL(5,2) NOT NULL,
  CREATION_DATE DATETIME NOT NULL,
  PRIMARY KEY (ID_ORDER),
  CONSTRAINT ID_ORDER_PERSON FOREIGN KEY (ID_PERSON) REFERENCES PERSON (ID_PERSON)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM (
  ID_ORDER_ITEM INT NOT NULL AUTO_INCREMENT,
  ID_ORDER INT NOT NULL,
  ID_DISC INT NOT NULL,
  QTD INT NOT NULL,
  UNIT_PRICE DECIMAL(5,2) NOT NULL,
  TOTAL DECIMAL(5,2) NOT NULL,
  CASHBACK DECIMAL(5,2) NOT NULL,
  CASHBACK_TOTAL DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (ID_ORDER_ITEM),
  CONSTRAINT ID_ORDER_ITEM_DISC FOREIGN KEY (ID_DISC) REFERENCES DISC (ID_DISC),
  CONSTRAINT ID_ORDER_ITEM_ORDER FOREIGN KEY (ID_ORDER) REFERENCES VD_ORDER (ID_ORDER)
);

INSERT INTO VD_ORDER (ID_PERSON, TOTAL, CASHBACK_TOTAL, CREATION_DATE) VALUES (1, 51, 5.1, sysdate());
INSERT INTO ORDER_ITEM (ID_ORDER, ID_DISC, QTD, UNIT_PRICE, TOTAL, CASHBACK, CASHBACK_TOTAL)
  VALUES ((SELECT ID_ORDER FROM VD_ORDER WHERE ID_PERSON = 1 AND TOTAL = 51 AND CASHBACK_TOTAL = 5.1), 1, 2, 25.5, 51, 10, 5.1);
