spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    name: vdsale
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:vdsale;Mode=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8

